---
- hosts: all

  tasks:

  - name: Installing the latest version of Filebeat...
    yum:
      name: filebeat
      state: latest

  - name: Block output port to Elasticsearch...
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^hosts: ["localhost:9200"]'
      insertafter: '^hosts: ["localhost:9200"]'
      line: '#hosts: ["localhost:9200"]'
      
  - name: Block output to Elasticsearch...
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^output.elasticsearch:'
      insertafter: '^output.elasticsearch:'
      line: '#output.elasticsearch:'
      
  - name: Open output port to Logstash...
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#hosts: ["localhost:5044"]'
      insertafter: '#hosts: ["localhost:5044"]'
      line: 'hosts: ["localhost:5044"]'
      
  - name: Open output to Logstash...
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^#output.logstash:'
      insertafter: '#output.logstash:'
      line: 'output.logstash:' 
      
  - name: Enabling Filebeat modules, loading template and starting up Filebeat...
    shell: |
      filebeat modules enable system
      filebeat setup --template -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]'
      filebeat setup -e -E output.logstash.enabled=false -E output.elasticsearch.hosts=['localhost:9200'] -E setup.kibana.host=localhost:5601
      systemctl start filebeat
      systemctl enable filebeat
