---
- hosts: all

  tasks:

  - name: Install the latest version of kibana
    yum:
      name: kibana
      state: latest
      
  - name: Starting and enabling Kibana...
    shell: |
      systemctl enable kibana
      systemctl start kibana
      
  - name: Creating a user for Kibana...
    shell: |
      echo "kibanaadmin:`openssl passwd -apr1 kibanaadmin`" | sudo tee -a /etc/nginx/htpasswd.users
      
  - name: Creating the Nginx conf file for Kibana...
    shell: |
      echo > /etc/nginx/conf.d/kibana.conf
      
  - name: Add info for Kibana conf file...
    blockinfile: |
      dest=/etc/nginx/conf.d/kibana.conf
      content="server {
         listen 80;
         auth_basic_user_file /etc/nginx/htpasswd.users;
         location / {
         proxy_pass http://localhost:5601;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_cache_bypass $http_upgrade;
         }
         }"
         
  - name: And mising parameter for Nginx conf file...
    lineinfile:
      path: /etc/nginx/conf.d/kibana.conf
      regexp: '^listen 80; '
      insertafter: '^listen 80; '
      line: 'auth_basic "Restricted Access";'
      
  - name: Restart Nginx and configure SElinux policy to allow Nginx to access the proxied service...
    shell: |
      systemctl restart nginx
      setsebool httpd_can_network_connect 1 -P
