---
- hosts: all

  tasks:
      
  - name: Block output to Elasticsearch...
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^output.elasticsearch:'
      line: '#output.elasticsearch:'
      
  - name: Block output port to Elasticsearch...
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      regexp: '^\\hosts:\\s["localhost:9200"]'
      line: '#hosts:\\s["localhost:9200"]'
