---
- hosts: all

  tasks:

  - name: Refreshing file /etc/nginx/conf.d/kibana.conf
    file:
      path: /etc/nginx/conf.d/kibana.conf
      state: absent 
      
  - name: Creating the Nginx conf file for Kibana...
    shell: |
      echo > /etc/nginx/conf.d/kibana.conf
      
  - name: Add info for Kibana conf file...
    blockinfile: |
      dest=/etc/nginx/conf.d/kibana.conf
      content="server {
         listen 81;
         
         auth_basic_user_file /etc/nginx/htpasswd.users;
         location / {
         proxy_pass http://localhost:5601;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_cache_bypass $http_upgrade;
         }
         }"
         
  - name: And mising parameter for Nginx conf file...
    lineinfile:
      path: /etc/nginx/conf.d/kibana.conf
      regexp: '^listen '
      insertafter: '^listen 81; '
      line: 'auth_basic "Restricted Access";'
      
  - name: Restart Nginx and configure SElinux policy to allow Nginx to access the proxied service...
    shell: |
      systemctl restart nginx
